FROM python:3.8-buster

ENV DEBIAN_FRONTEND noninteractive

COPY script/chrome_setup.bash /
RUN /chrome_setup.bash

RUN mkdir /app
WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY requirements-dev.txt .
RUN pip install -r requirements-dev.txt

ARG SECRET_KEY=blank
ARG ALLOW_PLAIN=TRUE

ENV VEGALITE_SERVER_PRODUCTION=FALSE VEGALITE_SERVER_ALLOW_PLAIN_SPEC=$ALLOW_PLAIN VEGALITE_SERVER_SECRET_KEY=$SECRET_KEY
